### ISSUE TITLE
Does reducing the number of duplicates improve `npm install` or `shrinkwrap` running time?

### ISSUE THREAD

**Issue by khoomeister** [timoxley/pkgcount#9]
I'm guessing the npm cache alleviates alot of these issues, but just wondering, have you done any benchmarks to see that reducing duplicates improves performance of `npm install` (useful for CI & deployments)?

**Comment by timoxley** [comment]
Unfortunately, you can't deduplicate *before* you've run `npm install`, deduplication can only apply *after* `npm install` has finished, so it can't possibly improve install time. Note there's a new install algorithm going into npm version 3 which will include far less duplication. Deduplication can very significantly decrease the total size of a deployment though.

**Comment by khoomeister** [comment]
Hey @timoxley, have you noticed improvements in deployment times since deduping?

**Comment by khoomeister** [comment]
BTW, thanks for the note re:npm 3

**Comment by timoxley** [comment]
dedupe shaves a few hundred megabytes off one of my projects, makes a difference when moving archives around.

**Comment by khoomeister** [comment]
Wow OK, nice to know!  Thanks man.

BTW, you did a good job on the recent nodeup podcast - gotta hear more from down under :smiley:
